services:
  backend-dev:
    profiles: ["dev"]
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    env_file:
      - .env
    volumes:
      - ./apps/backend:/app

  frontend-dev:
    profiles: ["dev"]
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - backend-dev
    command: ["npm", "run", "dev", "--", "--host"]

  backend-prod:
    profiles: ["prod"]
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    restart: always
    env_file:
      - .env.prod
    environment:
      - PORT=${DJANGO_PORT}

  frontend-prod:
    profiles: ["prod"]
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
    env_file:
      - .env
    depends_on:
      - backend-prod
