services:
  frontend-dev:
    profiles: ["dev"]
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

  frontend-prod:
    profiles: ["prod"]
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  backend-dev:
    profiles: ["dev"]
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./apps/backend:/app
