# Use slim Python image
FROM python:3.12-slim

# Set working directory inside container
WORKDIR /app

# Install system deps (psycopg2 needs these if you add Postgres later)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Set environment variables (Django will still read .env if present)
ENV PYTHONUNBUFFERED=1

# Run Django dev server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
